/* -----------------------------------------
    Contributors: Kevin Usuanlele / Scott Weaver
    ID's: 3103649 / 3144661
    Date: May 7, 2026
    Program: userclean.c
    Description:
    Reference(s):
------------------------------------------*/
