/* -----------------------------------------
    Contributors: Kevin Usuanlele / Scott
    ID's: 3103649 / 
    Date: May 7, 2026
    Program: userclean.c
    Description:
    Reference(s):
------------------------------------------*/